@startuml

hide empty members

class Gasolinera {
    - String id
    - String rotulo
    - String cp
    - String direccion
    - String municipio
    - double gasoleoA
    - double gasolina95E5
}

class GasolinerasResponse {
    - String fecha
    - String nota
    - String consulta
}

GasolinerasResponse *-- "*" Gasolinera : gasolineras

@enduml